### ISSUE TITLE
Cannot Run RN 0.59 CLI's 'run-ios' on xCode 13

### ISSUE THREAD

**Issue by woodrufs** [react-native-community/cli#1474]
I am maintaining an app that still runs on react native 0.59. I recently upgraded my MacBook to Big Sur, and now I am getting issues attempting to run my react native app that is on 0.59.10. Our script in package.json to run a version of our iOS app looks like:
```
"ios-debug": "node node_modules/react-native/local-cli/cli.js run-ios"
```
I am getting the following error after upgrading to Big Sur and xCode 13:
```
info Found Xcode workspace {APPNAME}.xcworkspace
xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
error Command failed: xcrun instruments -s
xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
```

I see this tool (instruments) has been removed from xCode. Since @react-native-community/cli is a transitive library that react-native includes itself, how do I go about using a newer version of the CLI tools? I attempted to install `@react-native-community/cli-platform-ios` to see if that would get me anywhere, but I had no luck finding a replacement to the `node node_modules/react-native/local-cli/cli.js run-ios` that the `ios-debug` script runs.
Does anyone have any advice? We are in the middle of upgrading said app, but we would really like to continue make changes to our existing app until our updated app is ready. Any help is really appreciated, thank you!

**Comment by cbrevik** [comment]
We're running RN `0.63.1` with the same issue.

Looks like in Xcode 13 `instruments` was removed, which will possibly mean that this no longer works for any version?

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes
>The deprecated instruments command-line tool has been removed; instead, use xctrace. (74412969)

And seems like it is used in the CLI here:
https://github.com/react-native-community/cli/blob/master/packages/platform-ios/src/commands/runIOS/index.ts#L402

**Comment by thymikee** [comment]
I believe it was fixed somewhere around 0.64. You can check the release notes of the CLI and re-apply the fix to older CLI versions?

**Comment by Mateoooo** [comment]
I have the same issue but only when I trying run app on iPhone.
RN `0.63.4`

**Comment by arufian** [comment]
> I believe it was fixed somewhere around 0.64. Can you check the release notes of the CLI and re-apply the fix to older CLI versions?

Nope, I already on the latest version. It still not working.
as @cbrevik said above, `instrument` was removed by Apple on XCode 13. 
CLI team should update their code to make it work. 🙏

**Comment by devxoul** [comment]
You may check my comment here: https://github.com/facebook/react-native/issues/32255#issuecomment-932039063

**Comment by ChauVV** [comment]
hit same error
