### ISSUE TITLE
Android install fails: getInstallApkName computes incorrect APK path for flavor+buildType

### ISSUE THREAD

**Issue by douglasjunior** [react-native-community/cli#2709]
## Environment

```
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✖ JDK - Required to compile Java code
   - Version found: 21.0.4
   - Version supported: >= 17 <= 20
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ .xcode.env - File to customize Xcode environment

Errors:   1
Warnings: 0
```

> Despite the warning about the Java 21, everything works fine.

## Description

We are trying to configure multiple Android flavors to support different branding and features, but we are encountering issues with the build process via CLI.

> We have used this exactly same configuration before without issues on older versions of the CLI.

When we run the following command:

```
npx react-native run-android --mode=whitelabelDebug --appId=br.com.example.whitelabel --appIdSuffix=develop
```

The native build finishes successfully and the app is installed on device, but the CLI crashes.

Error from `getInstallApkName` function on `commands/runAndroid/tryInstallAppOnDevice.js`:

```log
BUILD SUCCESSFUL in 45s
511 actionable tasks: 38 executed, 473 up-to-date
info Connecting to the development server...
👉 getInstallApkName args: { appName: 'app',  adbPath: '/Users/user/Library/Android/sdk/platform-tools/adb',  variant: 'whitelabeldebug',  device: 'RXCW50E1E7P',  buildDirectory: '/path/to/my-app/android/app/build/outputs/apk/whitelabeldebug' }
👉 apk path: /path/to/my-app/android/app/build/outputs/apk/whitelabeldebug/app-whitelabeldebug.apk
error Failed to install the app on the device.
Error: Could not find the correct install APK file.
    at getInstallApkName (/path/to/my-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/tryInstallAppOnDevice.js:87:9)
    at tryInstallAppOnDevice (/path/to/my-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/tryInstallAppOnDevice.js:50:23)
    at installAndLaunchOnDevice (/path/to/my-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:243:38)
    at runOnSpecificDevice (/path/to/my-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:233:7)
    at buildAndRun (/path/to/my-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:174:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Command.handleAction (/path/to/my-app/node_modules/@react-native-community/cli/build/index.js:139:9)
info Run CLI with --verbose flag for more details.
```

⚠️ Note that the CLI is trying to get the APK from `android/app/build/outputs/apk/whitelabeldebug/app-whitelabeldebug.apk`, but the correct path is `android/app/build/outputs/apk/whitelabel/debug/app-whitelabel-debug.apk`.

## Reproducible Demo

Just config the Android variants on `app/build.gradle`:

```groovy
android {
    // ...

    signingConfigs {
        develop {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        homolog {
            storeFile file(localProperties.getProperty("homolog.storeFile", "debug.keystore"))
            storePassword localProperties.getProperty("homolog.storePassword", "android")
            keyAlias localProperties.getProperty("homolog.keyAlias", "androiddebugkey")
            keyPassword localProperties.getProperty("homolog.keyPassword", "android")
        }
        release {
            storeFile file(localProperties.getProperty("release.storeFile", "debug.keystore"))
            storePassword localProperties.getProperty("release.storePassword", "android")
            keyAlias localProperties.getProperty("release.keyAlias", "androiddebugkey")
            keyPassword localProperties.getProperty("release.keyPassword", "android")
        }
    }
    flavorDimensions "version"
    productFlavors {
        whitelabel {
            dimension "version"
            applicationId "br.com.example.whitelabel"
            manifestPlaceholders = [appName: "Card"]
        }
        another {
            dimension "version"
            applicationId "br.com.example.another"
            manifestPlaceholders = [appName: "Another Cards"]
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.develop
            debuggable true

            applicationIdSuffix ".develop"
            manifestPlaceholders = [appNameSuffix: " Debug"]
        }
        developRelease {
            initWith release
            matchingFallbacks = ['release']

            signingConfig signingConfigs.develop
            applicationIdSuffix ".develop"
            manifestPlaceholders = [appNameSuffix: " Develop"]
        }
        homologRelease {
            initWith release
            matchingFallbacks = ['release']

            signingConfig signingConfigs.homolog
            applicationIdSuffix ".homolog"
            manifestPlaceholders = [appNameSuffix: " Homolog"]
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

            debuggable false
            applicationIdSuffix ""
            manifestPlaceholders = [appNameSuffix: ""]
        }
    }
}
```

And then, run on terminal:

```sh
npx react-native run-android --mode=whitelabelDebug --appId=br.com.example.whitelabel --appIdSuffix=develop
```

**Comment by douglasjunior** [comment]
Fixed on version v20.0.1 #2324

**Comment by reeywhaar** [comment]
Version 20.1.1, still not fixed. Given `--mode clientStagingDebug`. buildDirectory is expected to be `app/android/app/build/outputs/apk/clientStaging/debug`, but `tryInstallAppOnDevice` looks at `app/android/app/build/outputs/apk/client/staging/debug`
